--- #YAML:1.0
name:               Test-WWW-Selenium-HTML
version:            0.01
abstract:           Run Selenium HTML tests directly
author:
    - Tom Harrison <cpan@apnic.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Daemon:         0
    Params::Validate:     0
    Test::Builder:        0.90
    Test::More:           0.90
    Test::Pod:            0.95
    Test::WWW::Selenium:  0
    Time::HiRes:          0
    XML::LibXML:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
