---
abstract: 'Run Selenium HTML tests directly'
author:
  - 'Tom Harrison <cpan@apnic.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-WWW-Selenium-HTML
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Daemon: 0
  Params::Validate: 0
  Test::Builder: 0.90
  Test::More: 0.90
  Test::Pod: 0.95
  Test::WWW::Selenium: 0
  Time::HiRes: 0
  XML::LibXML: 0
resources:
  repository: https://github.com/APNIC-net/p5-Test-WWW-Selenium-HTML
version: 0.02
